title: Rooms
views:

  - title: Livingroom
    cards:

      - type: entities
        entities:
          - entity: light.livingroom_ceiling_1
            name: ceiling_1
          - entity: light.livingroom_ceiling_1_nightlight
            name: nightlight_1
          - entity: light.livingroom_ceiling_1_ambilight
            name: ambilight_1
          - entity: light.livingroom_ceiling_2
            name: ceiling_2
          - entity: light.livingroom_ceiling_2_nightlight
            name: nightlight_2
          - entity: light.livingroom_ceiling_2_ambilight
            name: ambilight_2
          - entity: light.livingroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.livingroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.livingroom_motion_1_motion
            name: motion
          - entity: sensor.livingroom_motion_1_battery
            name: battery
          - entity: sensor.livingroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: sensor.livingroom_air_temperature
            name: temperature
          - entity: sensor.livingroom_air_humidity
            name: humidity
          - entity: sensor.livingroom_air_co2
            name: co2
          - entity: sensor.livingroom_air_pm10
            name: pm10
          - entity: sensor.livingroom_air_pm25
            name: pm25
          - entity: sensor.livingroom_air_etvoc
            name: etvoc
          - entity: sensor.livingroom_air_battery
            name: battery
        title: Air

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_5bd0_switch
            name: status
          - entity: light.chuangmi_212a01_5bd0_indicator_light
            name: light
          - entity: sensor.chuangmi_212a01_5bd0_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_5bd0_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_5bd0_temperature
            name: power
        title: Power_eGPU

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_f148_switch
            name: status
          - entity: light.chuangmi_212a01_f148_indicator_light
            name: light
          - entity: sensor.chuangmi_212a01_f148_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_f148_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_f148_temperature
            name: power
        title: Power_LCD

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_d2fd_switch
            name: status
          - entity: light.chuangmi_212a01_d2fd_indicator_light
            name: light
          - entity: sensor.chuangmi_212a01_d2fd_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_d2fd_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_d2fd_temperature
            name: power
        title: Power_Table

      - type: entities
        entities:
          - entity: switch.chuangmi_212a01_690a_switch
            name: status
          - entity: light.chuangmi_212a01_690a_indicator_light
            name: light
          - entity: sensor.chuangmi_212a01_690a_electric_power
            name: current
          - entity: sensor.chuangmi_212a01_690a_power_cost_month
            name: month
          - entity: sensor.chuangmi_212a01_690a_temperature
            name: power
        title: Power_MOTU

      - type: entities
        entities:
          - entity: switch.livingroom_power_5_plug
            name: status
          - entity: sensor.livingroom_power_5_energy
            name: energy
          - entity: sensor.livingroom_power_5_power
            name: power
        title: Power_Amp

      - type: entities
        entities:
          - entity: switch.livingroom_power_6_plug
            name: status
          - entity: sensor.livingroom_power_6_energy
            name: energy
          - entity: sensor.livingroom_power_6_power
            name: power
        title: Power_TV

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.livingroom
            live_provider: go2rtc

  - title: Bedroom
    cards:

      - type: entities
        entities:
          - entity: light.bedroom_ceiling
            name: ceiling
          - entity: light.bedroom_ceiling_nightlight
            name: nightlight
          - entity: light.bedroom_ceiling_ambilight
            name: ambilight
          - entity: binary_sensor.bedroom_ceiling_nightlight
            name: nightlight
          - entity: light.bedroom_strip
            name: strip
        title: Light

      - type: entities
        entities:
          - entity: cover.bedroom_curtain_motor
            name: motor
        title: Curtain

      - type: entities
        entities:
          - entity: binary_sensor.bedroom_motion_1_motion
            name: motion
          - entity: sensor.bedroom_motion_1_battery
            name: battery
          - entity: sensor.bedroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: sensor.bedroom_temperature
            name: temperature
          - entity: sensor.bedroom_temperature_humidity
            name: humidity
          - entity: sensor.bedroom_temperature_pressure
            name: pressure
          - entity: sensor.bedroom_temperature_battery
            name: battery
        title: Temperature

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.bedroom
            live_provider: go2rtc

  - title: Kitchen
    cards:

      - type: entities
        entities:
          - entity: sensor.kitchen_kettle_state
            name: State
          - entity: binary_sensor.kitchen_kettle_power
            name: Power
          - entity: sensor.kitchen_kettle_temperature
            name: Temperature
        title: Kettle

      - type: entities
        entities:
          - entity: light.kitchen_light_1_light
            name: point1
          - entity: light.kitchen_light_2_light
            name: point2
          - entity: light.kitchen_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: light.kitchen_bulb_1_light
            name: bulb1
          - entity: light.kitchen_bulb_2_light
            name: bulb2
          - entity: light.kitchen_bulb_3_light
            name: bulb3
          - entity: light.kitchen_bulb_4_light
            name: bulb4
          - entity: light.kitchen_bulb_5_light
            name: bulb5
          - entity: light.kitchen_bulb_6_light
            name: bulb6
          - entity: light.1991481969963573248_light
            name: group
        title: chandelier

      - type: entities
        entities:
          - entity: switch.kitchen_relay_1_channel_1
            name: Channel1
          - entity: switch.kitchen_relay_1_channel_2
            name: Channel2
          - entity: sensor.kitchen_relay_1_current
            name: Current
          - entity: sensor.kitchen_relay_1_energy
            name: Energy
          - entity: sensor.kitchen_relay_1_power
            name: Power
          - entity: sensor.kitchen_relay_1_voltage
            name: Voltage
        title: Ledline

      - type: entities
        entities:
          - entity: select.chunmi_press2_f189_start_cook
            name: cook
          - entity: button.chunmi_press2_f189_cancel_cooking
            name: cancel
          - entity: sensor.chunmi_press2_f189_status
            name: status
        title: Cooker

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_1_motion
            name: motion
          - entity: sensor.kitchen_motion_1_battery
            name: battery
          - entity: sensor.kitchen_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.kitchen_motion_2_motion
            name: motion
          - entity: sensor.kitchen_motion_2_battery
            name: battery
          - entity: sensor.kitchen_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: sensor.kitchen_temperature
            name: temperature
          - entity: sensor.kitchen_temperature_humidity
            name: humidity
          - entity: sensor.kitchen_temperature_pressure
            name: pressure
          - entity: sensor.kitchen_temperature_battery
            name: battery
        title: Temperature

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.kitchen
            live_provider: go2rtc

  - title: Hallway
    cards:

      - type: entities
        entities:
          - entity: alarm_control_panel.6490c176b86e_alarm
            name: alarm
          - entity: switch.6490c176b86e_alarm_trigger
            name: alarm
        title: Gateway

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_1_motion
            name: motion
          - entity: sensor.hallway_motion_1_battery
            name: battery
          - entity: sensor.hallway_motion_1_illuminance
            name: illuminance
        title: Motion1

      - type: entities
        entities:
          - entity: binary_sensor.hallway_motion_2_motion
            name: motion
          - entity: sensor.hallway_motion_2_battery
            name: battery
          - entity: sensor.hallway_motion_2_illuminance
            name: illuminance
        title: Motion2

      - type: entities
        entities:
          - entity: binary_sensor.walkthrough_motion_1_motion
            name: motion
          - entity: sensor.walkthrough_motion_1_battery
            name: battery
          - entity: sensor.walkthrough_motion_1_illuminance
            name: illuminance
        title: Motion3

      - type: entities
        entities:
          - entity: light.hallway_light_1_light
            name: point1
          - entity: light.hallway_light_2_light
            name: point2
          - entity: light.hallway_light_3_light
            name: point3
          - entity: light.hallway_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: light.hallway_light_4_light
            name: point1
          - entity: light.walkthrough_light_1_light
            name: point2
          - entity: light.walkthrough_light_2_light
            name: point3
          - entity: light.walkthrough_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: sensor.hallway_button_action
            name: action
          - entity: sensor.hallway_button_battery
            name: battery
        title: Button

      - type: entities
        entities:
          - entity: sensor.hallway_vibration_action
            name: action
          - entity: sensor.hallway_vibration_battery
            name: battery
        title: Vibration

      - type: entities
        entities:
          - entity: vacuum.xiaomi_ov31cn_0c3c_robot_cleaner
            name: Clean
          - entity: button.xiaomi_ov31cn_0c3c_start_sweep
            name: Start
          - entity: button.xiaomi_ov31cn_0c3c_stop_and_gocharge
            name: Stop and go Charge
          - entity: button.xiaomi_ov31cn_0c3c_pause_sweeping
            name: Pause
          - entity: button.xiaomi_ov31cn_0c3c_continue_sweep
            name: Resume
          - entity: select.xiaomi_ov31cn_0c3c_sweep_mop_type
            name: Mode
          - entity: select.xiaomi_ov31cn_0c3c_mode
            name: Suction
          - entity: select.xiaomi_ov31cn_0c3c_clean_times
            name: Number of times
          - entity: sensor.xiaomi_ov31cn_0c3c_battery_level
            name: Battery level
          - entity: sensor.xiaomi_ov31cn_0c3c_charging_state
            name: Charging State
          - entity: sensor.xiaomi_ov31cn_0c3c_mop_life_level
            name: Mop Status
        title: Vacuum

      - type: entities
        entities:
          - entity: lock.hallway_lock
            name: Lock
        title: Lock

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.hallway
            live_provider: go2rtc

      - type: iframe
        name: Speedtest
        url: http://192.168.2.242:8081/
        aspect_ratio: 75%

  - title: Bathroom
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_motion_1_motion
            name: motion
          - entity: sensor.bathroom_motion_1_battery
            name: battery
          - entity: sensor.bathroom_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.bathroom_light_1_light
            name: point1
          - entity: light.bathroom_light_2_light
            name: point2
          - entity: light.bathroom_light_3_light
            name: point3
          - entity: light.bathroom_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.bathroom_relay_1_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_1_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_1_current
            name: Current
          - entity: sensor.bathroom_relay_1_energy
            name: Energy
          - entity: sensor.bathroom_relay_1_power
            name: Power
          - entity: sensor.bathroom_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: switch.bathroom_relay_2_channel_1
            name: Channel1
          - entity: switch.bathroom_relay_2_channel_2
            name: Channel2
          - entity: sensor.bathroom_relay_2_action
            name: Current
          - entity: sensor.bathroom_relay_2_energy
            name: Energy
          - entity: sensor.bathroom_relay_2_power
            name: Power
          - entity: sensor.bathroom_relay_2_voltage
            name: Voltage
        title: Towelheat

  - title: Toilet
    cards:

      - type: entities
        entities:
          - entity: binary_sensor.toilet_motion_1_motion
            name: motion
          - entity: sensor.toilet_motion_1_battery
            name: battery
          - entity: sensor.toilet_motion_1_illuminance
            name: illuminance
        title: Motion

      - type: entities
        entities:
          - entity: light.toilet_light_1_light
            name: point1
          - entity: light.toilet_light_2_light
            name: point2
          - entity: light.toilet_lights_light
            name: group
        title: Light

      - type: entities
        entities:
          - entity: switch.toilet_relay_1_channel_1
            name: Channel1
          - entity: switch.toilet_relay_1_channel_2
            name: Channel2
          - entity: sensor.toilet_relay_1_action
            name: action
          - entity: sensor.toilet_relay_1_current
            name: Current
          - entity: sensor.toilet_relay_1_energy
            name: Energy
          - entity: sensor.toilet_relay_1_power
            name: Power
          - entity: sensor.toilet_relay_1_voltage
            name: Voltage
        title: Hood

      - type: entities
        entities:
          - entity: binary_sensor.bathroom_moisture
            name: moisture
          - entity: sensor.bathroom_moisture_battery
            name: battery
        title: WaterLeak

  - title: Balcony
    cards:

      - type: entities
        entities:
          - entity: sensor.balcony_temperature
            name: temperature
          - entity: sensor.balcony_temperature_humidity
            name: humidity
          - entity: sensor.balcony_temperature_pressure
            name: pressure
          - entity: sensor.balcony_temperature_battery
            name: battery
        title: Temperature

      - type: entities
        entities:
          - entity: switch.zimi_v2_8df3_switch
            name: status
          - entity: light.zimi_v2_8df3_indicator_light
            name: light
          - entity: sensor.zimi_v2_8df3_store_powercost_today
            name: today
          - entity: sensor.zimi_v2_8df3_store_powercost_month
            name: month
          - entity: sensor.zimi_v2_8df3_electric_power
            name: power
          - entity: sensor.zimi_v2_8df3_surge_power
            name: surge
        title: Power_Server

      - type: custom:advanced-camera-card
        cameras:
          - camera_entity: camera.balcony
            live_provider: go2rtc
